# Use of BaseModel for data validation and serialization
# Use of Field for adding metadata and validation constraints to model fields   
# Use of computed_field for defining properties that are automatically calculated based on other fields in the model
# Use of Annotated for adding metadata to fields in a more concise way
# Use of Literal for defining fields that can only take specific literal values


from fastapi import FastAPI , Path , HTTPException , Query
from fastapi.responses import JSONResponse
from pydantic import BaseModel , Field, computed_field
from typing import Annotated , Literal, Optional
import json

app= FastAPI()

class Patient(BaseModel):

    # Annotated fields with descriptions and examples for better documentation in FastAPI. The Field function is used to provide additional metadata for each field, such as descriptions, examples, and validation constraints. This enhances the API documentation generated by FastAPI and helps users understand the expected input for each field.
    id: Annotated[str , Field(... , description= 'Unique patient identifier' , example = 'P001')]
    name: Annotated[str , Field(... , max_length=100, description="Full name of the patient, max 100 characters")]
    city: Annotated[str , Field(... , description= 'City of residence' , example = 'Gurgaon')]
    age: Annotated[int , Field(... , gt=0 , lt=120, description="Age of the patient and  must be between 1 and 120")]
    gender: Annotated[ Literal['male' , 'female' , 'other'] , Field(... , description= 'Gender of the patient' , example = 'male')]
    height: Annotated[float , Field(... , description= 'Height of the patient in centimeters' , example = 172.5)]
    weight: Annotated[float , Field(... , gt=0, description="Weight of the patient in kilograms and must be greater than zero" , example = 75.2)]

    # Here we are using computed_field decorator to calculate the BMI of a patient based on their weight and height. The BMI is calculated using the formula: weight (kg) / (height (m) ^ 2). The computed_field decorator allows us to define a property that is automatically calculated based on other fields in the model.
    @computed_field
    @property
    def bmi(self) -> float:
        bmi = round(self.weight/(self.height/100)**2,2)
        return bmi
    
    # Computed field for BMI category and what it does is to categorize the BMI of a patient into different categories such as Underweight, Normal weight, Overweight, and Obese based on the calculated BMI value. This provides additional information about the patient's health status based on their BMI.
    @computed_field
    @property
    def bmi_category(self) -> str:
        if self.bmi < 18.5:
            return 'Underweight'
        elif 18.5 <= self.bmi < 25:
            return 'Normal weight'
        elif 25 <= self.bmi < 30:
            return 'Overweight'
        else:
            return 'Obese'


# Upar humne pydantic ki help se ek Patient model banaya hai jisme humne various fields define kiye hain jaise id, name, city, age
# Ab hum apna endpoint banayenge jisme hum patient data ko load karenge ek JSON file se aur usko return karenge. Iske liye hum ek helper function load_data() banayenge jo 'patients.json' file se data load karega aur usko return karega. Phir hum ek endpoint banayenge '/view' jisme hum load_data() function ko call karenge aur uska result return karenge.


# Yaha pe hum ek aur pydantic model banayenge jiska naam hoga PatientUpdate. Ye model update ke liye use hoga jisme hum optional fields define karenge jisse ki user sirf unhi fields ko update kar sake jo wo chahte hain. Isme humne id field ko exclude kiya hai kyunki id ko update nahi karna chahiye. Iske alawa hum
class PatientUpdate(BaseModel):
    name: Annotated[Optional[str] , Field(None , max_length=100, description="Full name of the patient, max 100 characters")]
    city: Annotated[Optional[str] , Field(None , description= 'City of residence' , example = 'Gurgaon')]
    age: Annotated[Optional[int] , Field(None , gt=0 , lt=120, description="Age of the patient and  must be between 1 and 120")]
    gender: Annotated[Optional[ Literal['male' , 'female' , 'other']] , Field(None , description= 'Gender of the patient' , example = 'male')]
    height: Annotated[Optional[float] , Field(None , description= 'Height of the patient in centimeters' , example = 172.5)]
    weight: Annotated[Optional[float] , Field(None , gt=0, description ="Weight of the patient in kilograms and must be greater than zero" , example = 75.2)]

def load_data():
    with open('patients.json' , 'r') as f:
        data = json.load(f)

    return data

def save_data(data):
    with open('patients.json' , 'w') as f:
        json.dump(data , f )

@app.get("/")
def hello():
    return {"message" :"Hello world"}

# This endpoint is used to provide information about the API. When accessed, it returns a simple message indicating that the API is fully functional. This can be useful for testing and confirming that the API is up and running.
@app.get('/about')
def about():
    return {'message' : 'A fully functional'}

# This endpoint is used to view all the patient data. It loads the data from a JSON file using the load_data() function and returns it as a response. The load_data() function reads the contents of the 'patients.json' file and returns it as a Python dictionary, which is then returned by the endpoint when accessed.
@app.get('/view')
def view():
    data = load_data()
    return data


# This endpoint is used to view the details of a specific patient based on their ID. It takes a patient_id as a path parameter, loads all the patient data using the load_data() function, and checks if the provided patient_id exists in the data. If it does, it returns the details of that patient; otherwise, it raises an HTTPException with a 404 status code indicating that the patient was not found.
@app.get('/patient/{patient_id}')
def view_paient(patient_id : str = Path(... , description= 'ID of the patient in DB' , example= 'P003')):
    #load all the patients
    data = load_data()

    if patient_id in data:
        return data[patient_id]
    raise HTTPException(status_code=404 , detail= 'Patient not found')

@app.get('/sort')
def sort_patients(sort_by : str = Query(..., description = ' Sort on the basis of height , weight and bmi') , order : str = Query('asc' ,  description = ' Sort in ascendeng or descending order')):
 
    valid_fields = ['height' , 'weight' , 'bmi']

    if sort_by not in valid_fields:
        raise HTTPException(status_code=400 , detail =f'Invalid sort field select from {valid_fields}')

    if order not in ['asc' , 'desc']:
        raise HTTPException(status_code=400 , detail = 'Invalid sort order select from asc or desc')
    
    data = load_data()
    sort_order = True if order == 'desc' else False

    sorted_data = sorted(data.values() , key = lambda x : x.get(sort_by , 0) , reverse=sort_order)

    return sorted_data



@app.post('/create')
def create_patient(patient: Patient): # Here we are using the Patient model as a parameter in the create_patient endpoint. This allows us to automatically validate the incoming request data against the defined schema of the Patient model. When a POST request is made to this endpoint with patient data, FastAPI will parse the request body, validate it according to the Patient model, and if it's valid, it will create an instance of the Patient model with the provided data. If the data is invalid, FastAPI will return a 422 Unprocessable Entity error with details about what went wrong during validation.
    
    # load existing data
    data = load_data()

    # check if patient ID already exists
    if patient.id in data:
        raise HTTPException(status_code=400 , detail = 'Patient ID already exists')
    
    # new patient data to be added
    data[patient.id] = patient.model_dump(exclude=['id']) # this will convert the patient object to a dictionary format}

    # save the updated data back to the JSON file
    save_data(data)

    return JSONResponse( status_code=201 , content = {'message' : 'Patient created successfully' , 'patient_id' : patient.id})


@app.put('/edit/{patient_id}')
def update_patient(patient_id : str , patient_update: PatientUpdate):
    # load existing data
    data = load_data()

    # check if patient ID exists
    if patient_id not in data:
        raise HTTPException(status_code=404 , detail = 'Patient not found')

    # update the patient data with the provided fields

    #hume poore data me se patient_id ke corresponding data ko nikalna hai aur usko update karna hai. Iske liye hum existing_patient_data variable me data[patient_id] ko store karenge. Phir hum patient_update object ko dictionary me convert karenge using model_dump() method with exclude_unset=True option. Ye option ensure karta hai ki sirf wo fields include hon jo explicitly set kiye gaye hain PatientUpdate model me, aur unset fields ko exclude kar dega. Isse hum sirf unhi fields ko update karenge jo user ne provide kiye hain, aur baaki fields unchanged rahenge. Phir hum existing_patient_data me update karenge using a for loop that iterates over the items in patient_update_dict and updates the corresponding fields in existing_patient_data. Finally, we save the updated data back to the JSON file using save_data() function and return a JSONResponse indicating that the patient was updated successfully along with the patient_id.
    existing_patient_info = data[patient_id]
    
    # this will convert the patient_update object to a dictionary format and exclude unset fields tells use that we only want to include fields that have been explicitly set in the PatientUpdate model. This is important because we want to update only the fields that the user has provided in the request, and leave the other fields unchanged. By excluding unset fields, we ensure that we don't accidentally overwrite existing data with default values or None for fields that were not included in the update request.
    patient_update_dict = patient_update.model_dump(exclude_unset=True) 

    # yaha pe hum existing_patient_data me update karenge using a for loop that iterates over the items in patient_update_dict and updates the corresponding fields in existing_patient_data. Finally, we save the updated data back to the JSON file using save_data() function and return a JSONResponse indicating that the patient was updated successfully along with the patient_id.
    for field, value in patient_update_dict.items():
        existing_patient_info[field] = value

    
    # ab seen aisa hai ki agar humari height aur weight update hui hai to hamara bmi bhi change ho jayega 
    # isliye pehle hum iss existing_patient_info ka pydantic model create karenge jisse ki humara bmi calculate ho sake aur fir usko update karenge existing_patient_data me

    #existing_patient_info -> pydantic object -> updated bmi + verdict
    # hamare pydantic class me id field hai jo ki required hai aur hamare existing_patient_info me nahi hai isliye hum usko add karenge before creating the pydantic object
    existing_patient_info['id'] = patient_id
    patient_pydandic_obj = Patient(**existing_patient_info)
    #-> pydantic object -> dict
    existing_patient_info = patient_pydandic_obj.model_dump(exclude='id')

    # add this dict to data
    data[patient_id] = existing_patient_info

    # save data
    save_data(data)

    return JSONResponse(status_code=200, content={'message':'patient updated'})
    


@app.delete('/delete/{patient_id}')
def delete_patient(patient_id : str):

    # load existing data
    data = load_data()

    # check if patient ID exists
    if patient_id not in data:
        raise HTTPException(status_code=404 , detail = 'Patient not found')

    # delete the patient data
    del data[patient_id]

    # save the updated data back to the JSON file
    save_data(data)

    return JSONResponse(status_code=200 , content = {'message' : 'Patient deleted successfully' , 'patient_id' : patient_id})